[global] rebasing, trying to retry commiting from clean

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -1,41 +1,43 @@
 #!/usr/bin/bash
 
-SOURCE="/home/cyril/.dotfiles /home/cyril/.go/src/github.com/cyrinux /home/cyril/.cache/mail* /home/cyril/.tarsnap-backup /home/cyril/library/contacts /home/cyril/library/calendars /home/cyril/.dotfiles /home/cyril/.dotfiles-private"
-BACKUP_PATH="/home/cyril/Vault/backup_cyril_laptop_DONTREMOVE"
-BACKUP_DIR="$BACKUP_PATH/$(date +%Y-%m-%d)"
+SOURCE=".dotfiles .go/src/github.com/cyrinux .mail .cache/mail* .tarsnap.key library/contacts library/calendars .dotfiles .dotfiles-private .ssh .gnupg"
+BACKUP_PATH=("/home/cyril/Vault/backup_cyril_laptop_DONTREMOVE" "/run/media/cyril/PortableSSD/backup_cyril_laptop_DONTREMOVE")
 
-if [ ! -d $BACKUP_PATH ]; then
-  echo "Backup device '$BACKUP_PATH' does not exist, aborting. Start 'open-vault 120'"
-  exit 1
-fi
+for backup_path in "${BACKUP_PATH[@]}"; do
+    if [ ! -d $backup_path ]; then
+        echo "Backup device '$backup_path' does not exist, aborting. Start 'open-vault 120'"
+        exit 1
+    fi
+    BACKUP_DIR="${backup_path}/$(date +%Y-%m-%d)"
 
-if [ -d $BACKUP_DIR ]; then
-  read -p "Backup directory '$BACKUP_DIR' already exists, merge? [y/n] " -n 1 -r
-  echo
-  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-    echo "Aborted."
-    exit 1
-  fi
-fi
+    if [ -d $BACKUP_DIR ]; then
+        read -p "Backup directory '$BACKUP_DIR' already exists, merge? [y/n] " -n 1 -r
+        echo
+        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+            echo "Aborted."
+            exit 1
+        fi
+    fi
 
-[ ! -f /home/cyril/Vault/.lock  ] && vault!
+    [ ! -f /home/cyril/Vault/.lock ] && vault!
 
-echo -e "\nBackup STARTED\n\nSource(s):   $SOURCE\nDestination: $BACKUP_DIR\n"
-rsync -a --info=progress2 $SOURCE $BACKUP_DIR
-exitcode=$?
+    cd "$HOME"
+    echo -e "\nBackup STARTED\n\nSource(s):   $SOURCE\nDestination: $BACKUP_DIR\n"
+    rsync -a --info=progress2 $SOURCE $BACKUP_DIR
+    exitcode=$?
 
-if [ "$exitcode" -eq "0" ]; then
-  echo -e "\nBackup SUCCESSFUL"
-else
-  echo -e "\nBackup FAILED"
-fi
+    if [ "$exitcode" -eq "0" ]; then
+        echo -e "\nBackup SUCCESSFUL"
+    else
+        echo -e "\nBackup FAILED"
+    fi
 
-echo -e "\n-------------------------------------------------------------------"
+    echo -e "\n-------------------------------------------------------------------"
 
-echo -e "\nBackup size:\n"
-du -hs $BACKUP_DIR
+    echo -e "\nBackup size:\n"
+    du -hs $BACKUP_DIR
 
-echo -e "\nRemaining disk space\n"
-df -kh $BACKUP_PATH
-
+    echo -e "\nRemaining disk space\n"
+    df -kh $backup_path
+done
 exit $exitcode
