lot of thing updated

diff --git a/bin/grimshot b/bin/grimshot
--- a/bin/grimshot
+++ b/bin/grimshot
@@ -15,6 +15,7 @@
 ## `grimshot copy win` - to copy current window
 ## `grimshot save area` - to select area and save it to default file (Pictures/Grimshot-$datetime.png)
 ## `grimshot save screen ~/screenshot.png` - to save screenshot under ~/screenshot.png
+## `grimshot save output ~/screenshot.png` - to save screenshot under ~/screenshot.png
 ## `grimshot` - usage
 ## `grimshot check` - verify if tools are installed
 
@@ -23,7 +24,7 @@ SUBJECT=${2:-screen}
 FILE=${3:-$(xdg-user-dir PICTURES)/$(date +'Grimshot %Y-%m-%d %H-%M-%S.png')}
 if [ "$ACTION" = "usage" ] ; then
   echo "Usage:"
-  echo "  grimshot copy|save win|screen|area [FILE]"
+  echo "  grimshot copy|save win|screen|output|area [FILE]"
   echo "Troubleshoot:"
   echo "  grimshot check"
   exit
@@ -62,7 +63,10 @@ check() {
 takeScreenshot() {
   FILE=$1
   GEOM=$2
-  if [ -z "$GEOM" ]; then
+  OUTPUT=$3
+  if [ ! -z "$OUTPUT" ]; then
+    grim -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
+  elif [ -z "$GEOM" ]; then
     grim "$FILE" || die "Unable to invoke grim"
   else
     grim -g "$GEOM" "$FILE" || die "Unable to invoke grim"
@@ -90,18 +94,22 @@ elif [ "$SUBJECT" = "win" ] ; then
 elif [ "$SUBJECT" = "screen" ] ; then
   GEOM=""
   WHAT="Screen"
+elif [ "$SUBJECT" = "output" ] ; then
+  GEOM=""
+  OUTPUT=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused)' | jq -r '.name')
+  WHAT="$OUTPUT"
 else
   die "Unknown subject to take a screen shot from" "$SUBJECT"
 fi
 
 if [ "$ACTION" = "copy" ] ; then
   TMP=$(mktemp) || die "Unable to create temp file: is mktemp installed?"
-  takeScreenshot "$TMP" "$GEOM"
+  takeScreenshot "$TMP" "$GEOM" "$OUTPUT"
   wl-copy --type image/png < "$TMP"  || die "Clipboard error"
   rm "$TMP"
   notifyOk "$WHAT copied to buffer"
 else
-  if takeScreenshot "$FILE" "$GEOM"; then
+  if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
     TITLE="Screenshot of $SUBJECT"
     MESSAGE=$(basename "$FILE")
     notifyOk "$MESSAGE" "$TITLE"
