chore: force pre-commit run

diff --git a/.local/bin/backitup b/.local/bin/backitup
--- a/.local/bin/backitup
+++ b/.local/bin/backitup
@@ -50,7 +50,7 @@ VERBOSITY=1
 ###############################################################################
 
 usage() {
-    echo "Usage: backitup.sh [OPTION...]
+	echo "Usage: backitup.sh [OPTION...]
 Note that any command line arguments overwrite variables defined in the source.
 
 Options:
@@ -65,130 +65,130 @@ Options:
 }
 
 log() {
-    if [ "$1" -le "$VERBOSITY" ]; then
-        echo "$2"
-    fi
+	if [ "$1" -le "$VERBOSITY" ]; then
+		echo "$2"
+	fi
 }
 
 backup() {
-    # Execute the backup.
-    log 1 "Executing program: $BACKUP"
-    $BACKUP
-    # If the backup was succesful, store the current time.
-    if [ $? -eq 0 ]; then
-        log 2 'Program completed.'
-        date "$timeformat" > "$LASTRUN"
-    else
-        log 2 'Program failed.'
-    fi
-    exit
+	# Execute the backup.
+	log 1 "Executing program: $BACKUP"
+	$BACKUP
+	# If the backup was succesful, store the current time.
+	if [ $? -eq 0 ]; then
+		log 2 'Program completed.'
+		date "$timeformat" >"$LASTRUN"
+	else
+		log 2 'Program failed.'
+	fi
+	exit
 }
 
 on_battery() {
-    ac_status="/sys/class/power_supply/AC/online"
-    local result=false # Assume negative unless proven otherwise
-    if [ -e "$ac_status" ]; then
-        if [ "$(cat $ac_status)" = "0" ]; then
-            result=true
-        fi
-    fi
-    echo "$result"
+	ac_status="/sys/class/power_supply/AC/online"
+	local result=false # Assume negative unless proven otherwise
+	if [ -e "$ac_status" ]; then
+		if [ "$(cat $ac_status)" = "0" ]; then
+			result=true
+		fi
+	fi
+	echo "$result"
 }
 
 # Get any arguments.
 while getopts ":p:b:l:n:h:avq" opt; do
-    case $opt in
-        p)
-            PERIOD=$OPTARG
-            ;;
-        b)
-            BACKUP=$OPTARG
-            ;;
-        l)
-            LASTRUN=$OPTARG
-            ;;
-        n)
-            NOFILE=$OPTARG
-            ;;
-        v)
-            VERBOSITY=2
-            ;;
-        q)
-            VERBOSITY=0
-            ;;
-        a)
-            ACONLY=true
-            ;;
-        h)
-            usage
-            exit
-            ;;
-        :)
-            echo "Option -$OPTARG requires an argument.
+	case $opt in
+	p)
+		PERIOD=$OPTARG
+		;;
+	b)
+		BACKUP=$OPTARG
+		;;
+	l)
+		LASTRUN=$OPTARG
+		;;
+	n)
+		NOFILE=$OPTARG
+		;;
+	v)
+		VERBOSITY=2
+		;;
+	q)
+		VERBOSITY=0
+		;;
+	a)
+		ACONLY=true
+		;;
+	h)
+		usage
+		exit
+		;;
+	:)
+		echo "Option -$OPTARG requires an argument.
             "
-            usage
-            exit
-            ;;
-    esac
+		usage
+		exit
+		;;
+	esac
 done
 
 # Bail out if on battery power and we only want to run on AC.
 if [ "$(on_battery)" = true ] && [ "$ACONLY" = true ]; then
-    log 2 "On battery power. Bailing out."
-    exit
+	log 2 "On battery power. Bailing out."
+	exit
 fi
 
 # Set the format of the time string to store.
 if [ "$PERIOD" == "DAILY" ]; then
-    timeformat='+%Y%m%d'
+	timeformat='+%Y%m%d'
 elif [ "$PERIOD" == "WEEKLY" ]; then
-    timeformat='+%G-W%W'
+	timeformat='+%G-W%W'
 elif [ "$PERIOD" == "MONTHLY" ]; then
-    timeformat='+%Y%m'
+	timeformat='+%Y%m'
 else
-    timeformat='+%s'
+	timeformat='+%s'
 fi
 
 # If the file does not exist, perform the user requested action. If no action
 # was specified, exit.
 if [ ! -e "$LASTRUN" ]; then
-    if [ -n "$NOFILE" ]; then
-        eval $NOFILE
-    else
-        exit
-    fi
+	if [ -n "$NOFILE" ]; then
+		eval $NOFILE
+	else
+		exit
+	fi
 fi
 
 # If the file exists and is not empty, get the timestamp contained within it.
 if [ -s "$LASTRUN" ]; then
-    timestamp=$(eval cat \$LASTRUN)
+	timestamp=$(eval cat \$LASTRUN)
 
-    # If the backup period is daily, weekly or monthly, perform the backup if
-    # the stored timestamp is not equal to the current date in the same format.
-    if [ "$PERIOD" == "DAILY" ] || [ "$PERIOD" == "WEEKLY" ] || [ "$PERIOD" == "MONTHLY" ]; then
-        if [ "$timestamp" != $(date "$timeformat") ]; then
-            backup
-        else
-            log 2 "Already executed once for period $PERIOD. Exiting."
-            exit
-        fi
+	# If the backup period is daily, weekly or monthly, perform the backup if
+	# the stored timestamp is not equal to the current date in the same format.
+	if [ "$PERIOD" == "DAILY" ] || [ "$PERIOD" == "WEEKLY" ] || [ "$PERIOD" == "MONTHLY" ]; then
+		if [ "$timestamp" != $(date "$timeformat") ]; then
+			backup
+		else
+			log 2 "Already executed once for period $PERIOD. Exiting."
+			exit
+		fi
 
-    # If the backup period is not daily, perform the backup if the difference
-    # between the stored timestamp and the current time is greater than the
-    # defined period.
-    else
-        diff=$(($(date "$timeformat") - timestamp))
-        if [ "$diff" -gt "$PERIOD" ]; then
-            backup
-        else
-            log 2 "Executed less than $PERIOD seconds ago. Exiting."
-            exit
-        fi
-    fi
+	# If the backup period is not daily, perform the backup if the difference
+	# between the stored timestamp and the current time is greater than the
+	# defined period.
+	else
+		diff=$(($(date "$timeformat") - timestamp))
+		if [ "$diff" -gt "$PERIOD" ]; then
+			backup
+		else
+			log 2 "Executed less than $PERIOD seconds ago. Exiting."
+			exit
+		fi
+	fi
 fi
 
 # If the file exists but is empty, the script has never been run before.
 # Execute the backup.
 if [ -e "$LASTRUN" ]; then
-    backup
+	backup
 fi
diff --git a/.local/bin/backup b/.local/bin/backup
--- a/.local/bin/backup
+++ b/.local/bin/backup
@@ -5,44 +5,44 @@ SOURCE=".dotfiles .cache/mail* .cache/tarsnap.key library/contacts library/calen
 BACKUP_PATH=("/run/media/cyril/PortableSSD/backup_cyril_laptop_DONTREMOVE" "/run/media/cyril/SURVIVOR/backup_cyril_laptop_DONTREMOVE")
 
 for backup_path in "${BACKUP_PATH[@]}"; do
-    if [ ! -d $backup_path ]; then
-        echo "Backup device '$backup_path' does not exist, aborting. Start 'open-vault 120'"
-        continue
-    fi
-    BACKUP_DIR="${backup_path}/$(date +%Y-%m-%d)"
+	if [ ! -d $backup_path ]; then
+		echo "Backup device '$backup_path' does not exist, aborting. Start 'open-vault 120'"
+		continue
+	fi
+	BACKUP_DIR="${backup_path}/$(date +%Y-%m-%d)"
 
-    if [ -d $BACKUP_DIR ]; then
-        read -p "Backup directory '$BACKUP_DIR' already exists, merge? [y/n] " -n 1 -r
-        echo
-        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-            echo "Aborted."
-            exit 1
-        fi
-    fi
+	if [ -d $BACKUP_DIR ]; then
+		read -p "Backup directory '$BACKUP_DIR' already exists, merge? [y/n] " -n 1 -r
+		echo
+		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+			echo "Aborted."
+			exit 1
+		fi
+	fi
 
-    while true; do
-        [ -f ~/Vault/.lock ] && break
-        sleep 1
-    done
+	while true; do
+		[ -f ~/Vault/.lock ] && break
+		sleep 1
+	done
 
-    cd "$HOME"
-    echo -e "\nBackup STARTED\n\nSource(s):   $SOURCE\nDestination: $BACKUP_DIR\n"
-    rsync -a --delete --info=progress2 $SOURCE $BACKUP_DIR
-    exitcode=$?
+	cd "$HOME"
+	echo -e "\nBackup STARTED\n\nSource(s):   $SOURCE\nDestination: $BACKUP_DIR\n"
+	rsync -a --delete --info=progress2 $SOURCE $BACKUP_DIR
+	exitcode=$?
 
-    if [ "$exitcode" -eq "0" ]; then
-        echo -e "\nBackup SUCCESSFUL"
-    else
-        echo -e "\nBackup FAILED"
-    fi
+	if [ "$exitcode" -eq "0" ]; then
+		echo -e "\nBackup SUCCESSFUL"
+	else
+		echo -e "\nBackup FAILED"
+	fi
 
-    echo -e "\n-------------------------------------------------------------------"
+	echo -e "\n-------------------------------------------------------------------"
 
-    echo -e "\nBackup size:\n"
-    du -hs $BACKUP_DIR
+	echo -e "\nBackup size:\n"
+	du -hs $BACKUP_DIR
 
-    echo -e "\nRemaining disk space\n"
-    df -kh $backup_path
-    echo
+	echo -e "\nRemaining disk space\n"
+	df -kh $backup_path
+	echo
 done
 exit $exitcode
diff --git a/.local/bin/qutebrowser-update-useragent b/.local/bin/qutebrowser-update-useragent
--- a/.local/bin/qutebrowser-update-useragent
+++ b/.local/bin/qutebrowser-update-useragent
@@ -2,8 +2,8 @@
 
 chromium_version="$(pacman -Si chromium | grep Version | cut -d':' -f2 | cut -d'-' -f1 | tr -d '[:space:]')"
 [ -n "$chromium_version" ] || {
-    echo >&2 "error retrieving chromium version"
-    exit 1
+	echo >&2 "error retrieving chromium version"
+	exit 1
 }
 
 sed -ri "s|Chrome/[^ ]+|Chrome/$chromium_version|g" ~/.local/share/qutebrowser/greasemonkey/fingerprint-protector.js
diff --git a/.local/bin/waybar-updates b/.local/bin/waybar-updates
--- a/.local/bin/waybar-updates
+++ b/.local/bin/waybar-updates
@@ -3,63 +3,63 @@
 cache_path="${XDG_CACHE_HOME:-$HOME/.cache}/waybar-updates"
 
 case "$1" in
-    show)
-        if [ -f "$cache_path" ]; then
-            cat "$cache_path"
-        else
-            printf '{"text": "waybar-updates cache is missing"}\n'
-        fi
-        ;;
-    refresh)
-        repo_status="$(curl -s https://healthchecks.io/badge/953a414b-22f6-4e43-8365-0fa32c/3V1Imjf0-2/aur.json | jq -r '.status')"
-        pac="$(checkupdates)"
-        aur="$(aur repo -u)"
-        vcs="$(aur vercmp-devel)"
-        off="$(checkofficial)"
-        dif="$(pacdiff -o)"
-        reb="$(checkrebuild | egrep -v '(opencv|zoom|goland|ledger-live)')"
-        rep="$(repoctl status | grep -v 'On repo' | grep -v '^$' | grep -v 'Everything up-to-date' | sed 's/^\s*//g')"
+show)
+	if [ -f "$cache_path" ]; then
+		cat "$cache_path"
+	else
+		printf '{"text": "waybar-updates cache is missing"}\n'
+	fi
+	;;
+refresh)
+	repo_status="$(curl -s https://healthchecks.io/badge/953a414b-22f6-4e43-8365-0fa32c/3V1Imjf0-2/aur.json | jq -r '.status')"
+	pac="$(checkupdates)"
+	aur="$(aur repo -u)"
+	vcs="$(aur vercmp-devel)"
+	off="$(checkofficial)"
+	dif="$(pacdiff -o)"
+	reb="$(checkrebuild | egrep -v '(opencv|zoom|goland|ledger-live)')"
+	rep="$(repoctl status | grep -v 'On repo' | grep -v '^$' | grep -v 'Everything up-to-date' | sed 's/^\s*//g')"
 
-        pac_n=$(printf "$pac" | grep -c '^')
-        aur_n=$(printf "$aur" | grep -c '^')
-        vcs_n=$(printf "$vcs" | grep -c '^')
-        off_n=$(printf "$off" | grep -c '^')
-        dif_n=$(printf "$dif" | grep -c '^')
-        reb_n=$(printf "$reb" | grep -c '^')
-        rep_n=$(printf "$rep" | grep -c '^')
+	pac_n=$(printf "$pac" | grep -c '^')
+	aur_n=$(printf "$aur" | grep -c '^')
+	vcs_n=$(printf "$vcs" | grep -c '^')
+	off_n=$(printf "$off" | grep -c '^')
+	dif_n=$(printf "$dif" | grep -c '^')
+	reb_n=$(printf "$reb" | grep -c '^')
+	rep_n=$(printf "$rep" | grep -c '^')
 
-        text=""
-        tooltip=""
+	text=""
+	tooltip=""
 
-        [ -n "$text" -o -n "$rep" ] && text="/${rep_n}${text}"
-        [ -n "$rep" ] && tooltip="AUR repo needs cleaning:\n\n$rep\n\n${tooltip}"
-        [ -n "$text" -o -n "$off" ] && text="/${off_n}${text}"
-        [ -n "$off" ] && tooltip="Became official:\n\n$off\n\n${tooltip}"
-        [ -n "$text" -o -n "$reb" ] && text="/${reb_n}${text}"
-        [ -n "$reb" ] && tooltip="Rebuild required:\n\n$reb\n\n${tooltip}"
-        [ -n "$text" -o -n "$dif" ] && text="/${dif_n}${text}"
-        [ -n "$dif" ] && tooltip="pacdiff:\n\n$dif\n\n${tooltip}"
-        [ -n "$text" -o -n "$vcs" ] && text="/${vcs_n}${text}"
-        [ -n "$vcs" ] && tooltip="VCS:\n\n$vcs\n\n${tooltip}"
-        [ -n "$text" -o -n "$aur" ] && text="/${aur_n}${text}"
-        [ -n "$aur" ] && tooltip="AUR:\n\n$aur\n\n${tooltip}"
-        [ -n "$text" -o -n "$pac" ] && text="${pac_n}${text}"
-        [ -n "$pac" ] && tooltip="pacman:\n\n$pac\n\n${tooltip}"
+	[ -n "$text" -o -n "$rep" ] && text="/${rep_n}${text}"
+	[ -n "$rep" ] && tooltip="AUR repo needs cleaning:\n\n$rep\n\n${tooltip}"
+	[ -n "$text" -o -n "$off" ] && text="/${off_n}${text}"
+	[ -n "$off" ] && tooltip="Became official:\n\n$off\n\n${tooltip}"
+	[ -n "$text" -o -n "$reb" ] && text="/${reb_n}${text}"
+	[ -n "$reb" ] && tooltip="Rebuild required:\n\n$reb\n\n${tooltip}"
+	[ -n "$text" -o -n "$dif" ] && text="/${dif_n}${text}"
+	[ -n "$dif" ] && tooltip="pacdiff:\n\n$dif\n\n${tooltip}"
+	[ -n "$text" -o -n "$vcs" ] && text="/${vcs_n}${text}"
+	[ -n "$vcs" ] && tooltip="VCS:\n\n$vcs\n\n${tooltip}"
+	[ -n "$text" -o -n "$aur" ] && text="/${aur_n}${text}"
+	[ -n "$aur" ] && tooltip="AUR:\n\n$aur\n\n${tooltip}"
+	[ -n "$text" -o -n "$pac" ] && text="${pac_n}${text}"
+	[ -n "$pac" ] && tooltip="pacman:\n\n$pac\n\n${tooltip}"
 
-        tooltip="$(printf "$tooltip" | perl -pe 's/\n/\\n/g' | perl -pe 's/(?:\\n)+$//')"
+	tooltip="$(printf "$tooltip" | perl -pe 's/\n/\\n/g' | perl -pe 's/(?:\\n)+$//')"
 
-        if [ -z "$text" ]; then
-            printf '{"text": ""}\n' > "$cache_path"
-        elif [ -n "$repo_status" ] && [ "$repo_status" = "down" ]; then
-            printf "{\"text\": \"<span foreground='#928374'></span> %s\", \"tooltip\": \"%s\", \"class\": \"down\" }\n" "$text" "$tooltip" > "$cache_path"
-        else
-            printf "{\"text\": \"<span foreground='#928374'></span> %s\", \"tooltip\": \"%s\" }\n" "$text" "$tooltip" > "$cache_path"
-        fi
+	if [ -z "$text" ]; then
+		printf '{"text": ""}\n' >"$cache_path"
+	elif [ -n "$repo_status" ] && [ "$repo_status" = "down" ]; then
+		printf "{\"text\": \"<span foreground='#928374'></span> %s\", \"tooltip\": \"%s\", \"class\": \"down\" }\n" "$text" "$tooltip" >"$cache_path"
+	else
+		printf "{\"text\": \"<span foreground='#928374'></span> %s\", \"tooltip\": \"%s\" }\n" "$text" "$tooltip" >"$cache_path"
+	fi
 
-        pkill -RTMIN+1 -x waybar
-        ;;
-    *)
-        echo >&2 "Usage: $0 <show|refresh>"
-        exit 1
-        ;;
+	pkill -RTMIN+1 -x waybar
+	;;
+*)
+	echo >&2 "Usage: $0 <show|refresh>"
+	exit 1
+	;;
 esac
